### ISSUE TITLE
snapd-2.0.9.ebuild repoman errors

### ISSUE THREAD

**Issue by kefnab** [zyga/gentoo-snappy#1]
Repoman could not generate .ebuild manifest for `gentoo-snappy/app-emulation/snapd/snapd-2.0.9.ebuild`, built based off of @zyga [snapd repo](https://github.com/zyga/snapd-gentoo).

Not known if this build is still supported upstream.  [Repoman output available via pastebin](https://pastebin.com/raw/tb9x9nk1)

**Comment by kefnab** [comment]
Manifest properly built via repoman, and installed without errors as of [commit](https://github.com/zyga/gentoo-snappy/commit/3d4b2666a5f55c1bc22b8b8deca96eb6456d2753).  Both main packages emerge properly on ~amd64.

**Comment by kefnab** [comment]
Tested with `su -c "systemctl enable --now snapd.service"`
Downloaded and used `snap install nitrokey-app`, service worked and was able to manipulate password safe.

**Comment by zyga** [comment]
Woot. Thank you for checking this :)

I worked on update to snap-confine yesterday, I will update snapd today so that gentoo support is back to where it should be. If you would like to help please send me pull requests or advice on packaging, I will gladly take both.

**Comment by kefnab** [comment]
Thank you.  I'm self-taught, so if you have to roll-back something I did, don't feel bad.  With my limited programming experience, I will try to stick primarily to packaging - and being an ~amd64 test subject.  I will try a few more snaps, and then mark the packaging keyword as stable for amd64.
