### ISSUE TITLE
Only Systemd

### ISSUE THREAD

**Issue by ilnanny** [zyga/gentoo-snappy#21]
This package does not provide the files necessary for it to work without Systemd. 
Fix this please.

**Comment by sophietheopossum** [comment]
please refer to https://github.com/zyga/gentoo-snappy/issues/10 your issue appears to be a duplicate, you may want to close your issue and subscribe to that open issue (duplicate bugs help no one!)

**Comment by elsandosgrande** [comment]
@prototype99 Second that.
