### ISSUE TITLE
emerge failed during configure phase of snap-confine-1.0.41

### ISSUE THREAD

**Issue by kefnab** [zyga/gentoo-snappy#8]
> - Package:    sys-apps/snap-confine-1.0.41
> - Repository: gentoo-snappy
> - Maintainer: clayton.dobbs@gosecur.us
> - Upstream:   me@zygoon.pl
> - USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
> - FEATURES:   preserve-libs sandbox userpriv usersandbox
>   >>> Unpacking source...
>   >>> Unpacking 1.0.41.tar.gz to /var/tmp/portage/sys-apps/snap-confine-1.0.41/work
>   >>> Source unpacked in /var/tmp/portage/sys-apps/snap-confine-1.0.41/work
>   >>> Preparing source in /var/tmp/portage/sys-apps/snap-confine-1.0.41/work/snap-confine-1.0.41 ...
>   >>> Source prepared.
>   >>> Configuring source in /var/tmp/portage/sys-apps/snap-confine-1.0.41/work/snap-confine-1.0.41 ...
> - ERROR: sys-apps/snap-confine-1.0.41::gentoo-snappy failed (configure phase):
> -   no configure script found
>   *
> - Call stack:
> -          ebuild.sh, line 133:  Called src_configure
> -        environment, line 310:  Called econf '--disable-apparmor'
> -   phase-helpers.sh, line 668:  Called die
> - The specific snippet of code:
> -              die "no configure script found"
>   *
> - If you need support, post the output of `emerge --info '=sys-apps/snap-confine-1.0.41::gentoo-snappy'`,
> - the complete build log and the output of `emerge -pqv '=sys-apps/snap-confine-1.0.41::gentoo-snappy'`.
> - The complete build log is located at '/var/tmp/portage/sys-apps/snap-confine-1.0.41/temp/build.log'.
> - The ebuild environment file is located at '/var/tmp/portage/sys-apps/snap-confine-1.0.41/temp/environment'.
> - Working directory: '/var/tmp/portage/sys-apps/snap-confine-1.0.41/work/snap-confine-1.0.41'
> - S: '/var/tmp/portage/sys-apps/snap-confine-1.0.41/work/snap-confine-1.0.41'

Problem not present in snap-confine-1.0.40.

**Comment by zyga** [comment]
Hmm, thanks. Let me see if I missed something

**Comment by kefnab** [comment]
Bug closed with version bump.
